/* Next Cube Pro progression catalogs. Keep content here, not in script.js. */
(function () {
    const item = (id, ru, en, ruDesc, enDesc, reward, condition, requires = []) => ({
        id, name: { ru, en }, description: { ru: ruDesc, en: enDesc }, reward, condition, requires
    });

    const achievements = [
        item('a01','Первый скрамбл','First Scramble','1 сборка в таймере.','Complete 1 solve.',30,'total:1'),
        item('a02','Первая пятёрка','First Five','Получить первый AO5.','Get your first AO5.',40,'ao:5'),
        item('a03','Дюжина','The Dozen','Получить первый AO12.','Get your first AO12.',50,'ao:12'),
        item('a04','Первый полтинник','First Fifty','Сделать 50 сборок.','Complete 50 solves.',70,'total:50'),
        item('a05','Сотка в копилку','A Hundred','Получить первый AO100.','Get your first AO100.',100,'ao:100'),
        item('a06','Новичок','Beginner','250 сборок за всё время.','Complete 250 solves.',80,'total:250'),
        item('a07','Любитель','Enthusiast','500 сборок за всё время.','Complete 500 solves.',100,'total:500'),
        item('a08','Опытный','Experienced','1 000 сборок за всё время.','Complete 1,000 solves.',150,'total:1000'),
        item('a09','Ветеран таймера','Timer Veteran','2 500 сборок за всё время.','Complete 2,500 solves.',200,'total:2500'),
        item('a10','Маньяк скрамблов','Scramble Maniac','5 000 сборок за всё время.','Complete 5,000 solves.',250,'total:5000'),
        item('a11','Машина сборок','Solve Machine','10 000 сборок за всё время.','Complete 10,000 solves.',350,'total:10000'),
        ...[[60,40],[45,50],[30,70],[25,90],[20,120],[15,160],[12,200],[10,250],[8,300],[6,350]].map((x,i)=>item(`a${12+i}`,`Sub-${x[0]}`,`Sub-${x[0]}`,`Сборка быстрее ${x[0]} сек.`,`Solve faster than ${x[0]} seconds.`,x[1],`single:${x[0]}`)),
        item('a22','Уверенное начало','Confident Start','AO5 меньше 30 сек.','AO5 under 30 seconds.',60,'avg:5:30'),
        item('a23','Клуб Sub-20 (AO5)','Sub-20 Club (AO5)','AO5 меньше 20 сек.','AO5 under 20 seconds.',100,'avg:5:20'),
        item('a24','Клуб Sub-15 (AO5)','Sub-15 Club (AO5)','AO5 меньше 15 сек.','AO5 under 15 seconds.',150,'avg:5:15'),
        item('a25','Клуб Sub-10 (AO5)','Sub-10 Club (AO5)','AO5 меньше 10 сек.','AO5 under 10 seconds.',250,'avg:5:10'),
        item('a26','Стабильный Sub-20 (AO12)','Consistent Sub-20','AO12 меньше 20 сек.','AO12 under 20 seconds.',120,'avg:12:20'),
        item('a27','Стабильный Sub-15 (AO12)','Consistent Sub-15','AO12 меньше 15 сек.','AO12 under 15 seconds.',180,'avg:12:15'),
        item('a28','Стабильный Sub-10 (AO12)','Consistent Sub-10','AO12 меньше 10 сек.','AO12 under 10 seconds.',300,'avg:12:10'),
        item('a29','Хардкорный Sub-15 (AO100)','Hardcore Sub-15','AO100 меньше 15 сек.','AO100 under 15 seconds.',250,'avg:100:15'),
        item('a30','Мастер Sub-10 (AO100)','Sub-10 Master','AO100 меньше 10 сек.','AO100 under 10 seconds.',350,'avg:100:10'),
        ...[[3,50,'Первый шаг','First Step'],[7,100,'Недельный заплыв','Weekly Run'],[14,150,'Две недели в строю','Two Weeks Strong'],[30,250,'Месячная сталь','Monthly Steel'],[60,350,'Несокрушимый','Unbreakable']].map((x,i)=>item(`a${31+i}`,x[2],x[3],`Стрик ${x[0]} дней.`,`${x[0]}-day streak.`,x[1],`streak:${x[0]}`)),
        item('a36','Свой стиль','Your Style','Сменить тему оформления.','Change the interface theme.',30,'event:themeChanged'),
        item('a37','Настройка под себя','Made for You','Изменить настройки таймера.','Change timer settings.',30,'event:settingsChanged'),
        item('a38','Первая покупка','First Purchase','Купить любой предмет в магазине.','Buy any shop item.',50,'event:shopPurchase'),
        item('a39','Спасательный круг','Lifeline','Впервые применить заморозку.','Use a freeze for the first time.',50,'event:freezeUsed'),
        item('a40','Коллекционер','Collector','Накопить 2 000 монет одновременно.','Hold 2,000 coins at once.',150,'coins:2000'),
        item('a41','Никаких правил','No Rules','Исправить статус +2.','Remove a +2 status.',30,'event:plusTwoRemoved'),
        item('a42','Чистый протокол','Clean Protocol','50 сборок подряд без +2 и DNF.','50 consecutive clean solves.',100,'cleanStreak:50'),
        item('a43','Железные пальцы','Iron Fingers','100 сборок за один день.','100 solves in one day.',120,'dayCount:100'),
        item('a44','Сумасшедший день','Crazy Day','300 сборок за один день.','300 solves in one day.',100,'dayCount:300'),
        item('a45','Ультра-марафон','Ultra Marathon','500 сборок за один день.','500 solves in one day.',350,'dayCount:500'),
        item('a46','Разнообразие','Variety','Сборки в 3 разных дисциплинах.','Solve in 3 disciplines.',60,'disciplines:3'),
        item('a47','Мульти-мастер','Multi Master','По AO100 в трёх дисциплинах.','AO100 in 3 disciplines.',150,'aoDisciplines:100:3'),
        item('a48','Ночная смена','Night Shift','50 сборок с 01:00 до 05:00.','50 solves between 01:00 and 05:00.',80,'night:1:5:50'),
        item('a49','Фокус','Focus','20 сборок подряд в пределах ±0.8 сек от среднего.','20 consecutive solves within ±0.8s of their mean.',120,'focus:20:0.8'),
        item('a50','Абсолютное совпадение','Exact Match','Две сборки подряд с одинаковым временем до сотых.','Two consecutive solves equal to 0.01s.',200,'equalPair')
    ];

    const dailyRaw = [
      ['Пределы возможностей','Push the Limit','3 сборки быстрее PB + 0.5 сек.','3 solves faster than PB + 0.5s.','d01',['pb']],
      ['Шаг к прогрессу','Step Forward','Перебить PB единичной сборки.','Beat your single PB.','d02',['pb']],
      ['Стабильный день','Stable Day','Сделать AO5 быстрее текущего AO12.','Make AO5 faster than current AO12.','d03',['ao12']],
      ['Пик формы','Peak Form','Побить рекордный AO5.','Beat your best AO5.','d04',['bestAo5']],
      ['Идеальная сессия','Perfect Session','Сделать AO12 лучше текущего AO100.','Make AO12 better than current AO100.','d05',['ao100']],
      ['Выйти из зоны комфорта','Leave the Comfort Zone','AO5 быстрее AO100 − 1.5 сек.','AO5 faster than AO100 − 1.5s.','d06',['ao100']],
      ['Серийный прорыв','Series Breakthrough','Побить PB AO5 за день.','Beat your AO5 PB today.','d07',['bestAo5']],
      ['Железная консистентность','Iron Consistency','5 подряд быстрее AO100.','5 consecutive solves faster than AO100.','d08',['ao100']],
      ['На грани','On the Edge','Сборка быстрее PB + 0.2 сек.','Solve faster than PB + 0.2s.','d09',['pb']],
      ['Супер-сессия','Super Session','Побить лучший AO100.','Beat your best AO100.','d10',['bestAo100']],
      ['Стандарт дня','Daily Standard','Сделать средний суточный объём + 20%.','Do 20% more than your daily average.','d11',['dailyAverage']],
      ['Марафон 300','Marathon 300','300 сборок за день.','300 solves today.','d12',[]],
      ['Супер-марафон','Super Marathon','500 сборок за день.','500 solves today.','d13',[]],
      ['Темп 100','100 Pace','Сделать 100 сборок менее чем за 1.5 часа.','Complete 100 solves in under 1.5 hours.','d14',[]],
      ['Плотный график','Dense Schedule','50 сборок за 30 минут после первой сборки дня.','50 solves within 30 minutes of today’s first solve.','d15',[]],
      ['Заводной механизм','Clockwork','100 сборок без закрытия приложения.','100 solves without closing the app.','d16',[]],
      ['Двойная норма','Double Quota','В 2 раза больше сборок, чем вчера.','Twice as many solves as yesterday.','d17',['yesterdayCount']],
      ['Вечерний убой','Evening Grind','150 сборок с 18:00 до 23:59.','150 solves from 18:00 to 23:59.','d18',[]],
      ['Утренний разгон','Morning Boost','50 сборок до 12:00.','50 solves before noon.','d19',[]],
      ['Без остановки','Nonstop','40 минут суммарного времени сборок за день.','40 minutes of total solve time today.','d20',[]],
      ['Минимальный разброс','Minimum Spread','AO5 с разбросом менее 1.5 сек.','AO5 with a spread under 1.5s.','d21',[]],
      ['Стабильная десятка','Stable Ten','10 подряд в пределах ±1 сек от AO100.','10 consecutive within ±1s of AO100.','d22',['ao100']],
      ['Без саб-хлама','Clean Twelve','AO12 без +2 и DNF.','AO12 with no +2 or DNF.','d23',[]],
      ['Метроном','Metronome','3 подряд с разницей менее 0.3 сек.','3 consecutive solves within 0.3s.','d24',[]],
      ['Чистый лист','Clean Slate','50 сборок за день без DNF.','50 solves today with no DNF.','d25',[]],
      ['Контроль нервов','Nerve Control','После перерыва 3 часа сделать AO5 лучше дневного AO12.','After a 3-hour break, make AO5 better than today’s AO12.','d26',[]],
      ['Удержание высоты','Hold the Height','20 подряд быстрее AO100 + 2 сек.','20 consecutive faster than AO100 + 2s.','d27',['ao100']],
      ['Идеальный подсчёт','Perfect Count','AO12 с разбросом менее 1 сек.','AO12 with a spread under 1s.','d28',[]],
      ['Без фейлов','No Fails','100 сборок подряд без удаления.','100 consecutive solves without deleting one.','d29',[]],
      ['Финальный рывок','Final Push','Последние 5 лучше первых 5 дня.','Last 5 today better than the first 5.','d30',[]],
      ['Главная дисциплина','Main Discipline','150 сборок на основной дисциплине.','150 solves in your main discipline.','d31',['mainDiscipline']],
      ['Вторичный профиль','Secondary Profile','50 сборок на второй дисциплине.','50 solves in your secondary discipline.','d32',['secondaryDiscipline']],
      ['Смена обстановки','Change of Scene','По AO12 в трёх дисциплинах за день.','AO12 in three disciplines today.','d33',['threeDisciplines']],
      ['Рекорд в смежной','Side Record','Побить PB в неосновной дисциплине.','Beat a PB in a non-main discipline.','d34',['secondaryDiscipline']],
      ['Мастер Двушки','2x2 Master','100 сборок 2x2 за день.','100 2x2 solves today.','d35',[]],
      ['Бигкубы','Big Cubes','20 сборок на 4x4 и выше.','20 solves on 4x4 or larger.','d36',[]],
      ['Часовой спринт','Hourly Sprint','75 сборок за любые 60 минут.','75 solves within any 60-minute window.','d37',[]],
      ['Ритм без пауз','Unbroken Rhythm','10 сборок подряд с паузами не более 2 минут.','10 consecutive solves with gaps no longer than 2 minutes.','d38',[]],
      ['Разносторонность','Versatility','По 25 на 3x3, 2x2 и Pyraminx или 4x4.','25 each on 3x3, 2x2 and Pyraminx or 4x4.','d39',[]],
      ['Марафон бигкубов','Big Cube Marathon','30 минут суммарного времени 4x4/5x5.','30 minutes total solve time on 4x4/5x5.','d40',[]],
      ['Холодный старт','Cold Start','Первая сборка дня быстрее AO100.','First solve today faster than AO100.','d41',['ao100']],
      ['Реванш','Revenge','После +2 следующая сборка быстрее AO5.','After +2, next solve faster than AO5.','d42',['currentAo5']],
      ['Преодоление фейла','Overcome Failure','После DNF сделать 10 чистых быстрее AO100.','After DNF, make 10 clean solves faster than AO100.','d43',['ao100']],
      ['Серийная проверка','Series Check','3 раза получить AO5 лучше AO12.','Get AO5 better than AO12 three times.','d44',['ao12']],
      ['Ночной кубинг','Night Cubing','30 сборок с 00:00 до 04:00.','30 solves from 00:00 to 04:00.','d45',[]],
      ['Обед спидкубера','Speedcuber Lunch','50 сборок с 12:00 до 15:00.','50 solves from 12:00 to 15:00.','d46',[]],
      ['Пять из пяти','Five of Five','5 подряд, каждая быстрее предыдущей.','5 consecutive, each faster than the previous.','d47',[]],
      ['Стабильный марафон','Stable Marathon','AO100 с не более чем 2 DNF.','AO100 with no more than 2 DNFs.','d48',[]],
      ['Золотая середина','Golden Mean','Сборка в пределах ±0.05 сек от AO100.','Solve within ±0.05s of AO100.','d49',['ao100']],
      ['Закрытие дня','Closing Time','Завершить AO12 в последние 10 минут дня.','Complete AO12 in the last 10 minutes of the day.','d50',[]]
    ];
    const daily = dailyRaw.map(x => item(x[4],x[0],x[1],x[2],x[3],100,x[4],x[5]));
    window.PROGRESSION_CATALOG = { achievements, daily };
})();
